"use client";
import { API_URL } from "@/config/api";


import React, { createContext, useContext, useState, useEffect } from "react";

interface Language {
  name: string;
  code: string;
  direction: string;
}

interface Currency {
  code: string;
  name: string;
  symbol: string;
  rate?: number;
}

interface LanguageContextProps {
  lang: string;
  direction: string;
  currency: string;
  currencySymbol: string;
  currencyRate: number;
  translations: Record<string, string>;
  activeLanguages: Language[];
  currencies: Currency[];
  t: (key: string, defaultVal?: string) => string;
  changeLanguage: (code: string) => void;
  changeCurrency: (code: string) => void;
  convertPrice: (amountInUSD: number) => number;
  formatPrice: (amountInUSD: number) => string;
  loading: boolean;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<string>("EN");
  const [direction, setDirection] = useState<string>("LTR");
  const [currency, setCurrency] = useState<string>("USD");
  const [currencySymbol, setCurrencySymbol] = useState<string>("$");
  const [currencyRate, setCurrencyRate] = useState<number>(1.0);
  const [translations, setTranslations] = useState<Record<string, string>>({});
  const [activeLanguages, setActiveLanguages] = useState<Language[]>([]);
  const [currencies, setCurrencies] = useState<Currency[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  // Initialize from LocalStorage (safe client-side check)
  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedLang = localStorage.getItem("lang") || "EN";
      const savedDir = localStorage.getItem("direction") || "LTR";
      const savedCurr = localStorage.getItem("currency") || "USD";
      const savedSym = localStorage.getItem("currencySymbol") || "$";
      const savedRate = parseFloat(localStorage.getItem("currencyRate") || "1.0");

      setLang(savedLang);
      setDirection(savedDir);
      setCurrency(savedCurr);
      setCurrencySymbol(savedSym);
      setCurrencyRate(savedRate);

      // Set HTML dir attribute
      document.documentElement.dir = savedDir.toLowerCase();
    }
  }, []);

  // Fetch active languages and currencies list
  useEffect(() => {
    const fetchMetadata = async () => {
      try {
        // Fetch settings first to get defaults
        let defLang = "EN";
        let defCurr = "USD";
        let defSym = "$";
        let defRate = 1.0;
        let defDir = "LTR";

        const settingsRes = await fetch(`${API_URL}/settings`);
        if (settingsRes.ok) {
          const settingsData = await settingsRes.json();
          settingsData.forEach((setting: any) => {
            let val = setting.setting_value;
            if (typeof val === "string") {
              try { val = JSON.parse(val); } catch {}
            }
            if (setting.setting_key === "default_language") {
              defLang = val?.code || "EN";
            } else if (setting.setting_key === "default_currency") {
              defCurr = val?.code || "USD";
            }
          });
        }

        // Fetch active languages
        const langRes = await fetch(`${API_URL}/languages/active`);
        let activeLangsList: Language[] = [];
        if (langRes.ok) {
          activeLangsList = await langRes.json();
          setActiveLanguages(activeLangsList);
          
          const matchingLang = activeLangsList.find(l => l.code === defLang);
          if (matchingLang) {
            defDir = matchingLang.direction || "LTR";
          }
        }

        // Fetch currencies
        const currRes = await fetch(`${API_URL}/freelancer/currencies`);
        let activeCurrsList: Currency[] = [];
        if (currRes.ok) {
          activeCurrsList = await currRes.json();
          setCurrencies(activeCurrsList);
          
          const matchingCurr = activeCurrsList.find(c => c.code === defCurr);
          if (matchingCurr) {
            defSym = matchingCurr.symbol || "$";
            defRate = matchingCurr.rate !== undefined ? matchingCurr.rate : 1.0;
          }
        }

        // If local storage is empty, initialize with platform defaults
        if (typeof window !== "undefined") {
          const savedLang = localStorage.getItem("lang");
          const savedCurr = localStorage.getItem("currency");
          
          if (!savedLang) {
            setLang(defLang);
            setDirection(defDir);
            document.documentElement.dir = defDir.toLowerCase();
          }
          if (!savedCurr) {
            setCurrency(defCurr);
            setCurrencySymbol(defSym);
            setCurrencyRate(defRate);
          }
        }
      } catch (err) {
        console.error("Failed to load language/currency metadata:", err);
      }
    };
    fetchMetadata();
  }, []);

  // Fetch translation dictionary whenever active language changes
  useEffect(() => {
    const fetchTranslations = async () => {
      try {
        setLoading(true);
        const res = await fetch(`${API_URL}/translations/${lang}`);
        if (res.ok) {
          const data = await res.json();
          setTranslations(data);
        }
      } catch (err) {
        console.error("Failed to load translation map:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchTranslations();
  }, [lang]);

  const changeLanguage = (code: string) => {
    const uppercaseCode = code.toUpperCase();
    setLang(uppercaseCode);
    localStorage.setItem("lang", uppercaseCode);

    // Find and set direction
    const matchingLang = activeLanguages.find((l) => l.code === uppercaseCode);
    if (matchingLang) {
      const dir = matchingLang.direction || "LTR";
      setDirection(dir);
      localStorage.setItem("direction", dir);
      document.documentElement.dir = dir.toLowerCase();
    }
  };

  const changeCurrency = (code: string) => {
    const uppercaseCode = code.toUpperCase();
    setCurrency(uppercaseCode);
    localStorage.setItem("currency", uppercaseCode);

    const matchingCurr = currencies.find((c) => c.code === uppercaseCode);
    if (matchingCurr) {
      const sym = matchingCurr.symbol || "$";
      const rate = matchingCurr.rate !== undefined ? matchingCurr.rate : 1.0;
      setCurrencySymbol(sym);
      setCurrencyRate(rate);
      localStorage.setItem("currencySymbol", sym);
      localStorage.setItem("currencyRate", rate.toString());
    }
  };

  const convertPrice = (amountInUSD: number) => {
    return amountInUSD * currencyRate;
  };

  const formatPrice = (amountInUSD: number) => {
    const converted = convertPrice(amountInUSD);
    return `${currencySymbol}${converted.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

const STATIC_FALLBACK_DICTIONARY: Record<string, Record<string, string>> = {
  FR: {
    nav_categories: "Catégories",
    nav_talent: "Engager des Freelances",
    nav_projects: "Trouver des Projets",
    nav_gigs: "Explorer les Services",
    nav_blogs: "Blogs",
    btn_back: "Retour",
    btn_send_message: "Envoyer un Message",
    btn_hire_freelancer: "Engager ce Freelance",
    btn_browse: "Parcourir",
    btn_view_all_categories: "Voir toutes les catégories",
    categories_title: "Parcourir les catégories populaires",
    professional_bio: "Biographie Professionnelle",
    freelancer_metadata: "Détails du Freelance",
    core_competencies: "Compétences Clés",
    hourly_rate: "Taux Horaire",
    exp_level: "Niveau d'Expérience",
    active: "actif(s)",
    jobs: "projets",
    available_now: "Disponible Maintenant",
    currently_busy: "Occupé Actuellement",
    sign_in: "Se connecter",
    get_started: "Commencer",
    dashboard: "Tableau de bord",
    nav_view_profile: "Voir le profil",
    nav_logout: "Déconnexion",
    views: "vues",
    reviews: "avis",
    save_to_wishlist: "Ajouter aux favoris",
    saved: "Enregistré",
    search_gigs_placeholder: "Rechercher des services...",
    active_gigs: "services actifs",
    starting_at: "À partir de",
    btn_previous: "Précédent",
    btn_next: "Suivant",
    refine_search: "Affiner la recherche",
    filters: "Filtres",
    reset: "Réinitialiser",
    category: "Catégorie",
    subcategory: "Sous-catégorie",
    showing: "Affichage de",
    of: "sur",
    by: "Par",
    delivery: "livraison",
    hero_badge: "Le Top 3% des Freelances Mondiaux",
    hero_title: "Engagez des Freelances Experts Pour Votre Prochain Projet",
    hero_subtitle: "Connectez-vous avec des professionnels de premier ordre. Exécutez plus rapidement avec des talents vérifiés.",
    hero_search_placeholder: "Quelle compétence recherchez-vous ?",
    hero_search_btn: "Trouver un Talent",
    top_ranked_services: "Services les mieux notés",
    popular_services_title: "Services Populaires",
    view_all: "Tout Voir",
    active_marketplace_needs: "Besoins Actuels du Marché",
    recent_projects_title: "Derniers Projets",
    browse_all: "Tout Parcourir",
    featured_title: "Freelances En Vedette",
    featured_subtitle: "Professionnels les mieux notés prêts à commencer immédiatement.",
    featured_btn: "Voir tout",
    why_choose_title: "Pourquoi Choisir Freelancer ?",
    why_choose_subtitle: "Nous offrons une expérience transparente pour trouver, engager et gérer les meilleurs talents.",
    how_it_works_title: "Comment Ça Marche",
    btn_hire_now: "Engager Maintenant",
    footer_company: "Entreprise",
    footer_about: "À Propos",
    footer_careers: "Carrières",
    footer_contact: "Contact",
    footer_faq: "FAQ",
    footer_terms: "Conditions Générales",
    footer_connect: "Rejoignez-nous",
    footer_newsletter: "Newsletter",
    footer_mobile_app: "Application Mobile",
    pricing_package: "FORFAIT TARIFIAIRE",
    available_addons: "EXTRAS / OPTIONS DISPONIBLES",
    btn_order_service: "Commander le Service Maintenant",
    delivery_in: "Livraison en",
    days: "Jours",
    revisions: "Révisions",
    unlimited_revisions: "Révisions Illimitées",
    whats_included: "Ce qui est inclus",
    service_description: "Description du Service",
    faq_title: "Foire Aux Questions",
    customer_reviews: "Avis Clients",
    about_the_seller: "À Propos du Vendeur",
    starting_rate: "Tarif de Départ",
    view_full_profile: "Voir le Profil Complet",
    share_this_service: "Partager ce Service",
    core_expertise: "Compétences & Expertises Clés",
    footer_brand_desc: "Précision dans le professionnalisme. Rejoignez un marché organisé où des talents vérifiés créent des solutions clientes modernes.",
    footer_copyright: "© 2026 Freelancer Marketplace. Tous droits réservés.",
    no_reviews_yet: "AUCUN AVIS POUR LE MOMENT",
    similar_gigs_title: "Services Similaires Que Vous Pourriez Aimer",
    similar_gigs_subtitle: "Explorez les services d'autres professionnels d'élite dans la même catégorie.",
    no_similar_gigs_found: "AUCUN SERVICE SIMILAIRE TROUVÉ",
    promoted: "PROMU",
    hire_expert_freelancers: "Engager des Freelances Experts",
    promoted_desc: "Obtenez des solutions sur mesure adaptées précisément à votre budget et à vos délais.",
    hover_category_prompt: "Survolez n'importe quelle catégorie ci-dessus pour explorer les sous-catégories.",
    btn_back_to_projects: "Retour aux Projets",
    project_type: "Type de Projet",
    experience_level: "Niveau d'Expérience",
    duration: "Durée Estimée",
    location: "Emplacement",
    project_description: "Description du Projet",
    skills_required: "Compétences Requises",
    preferred_languages: "Langues Préférées",
    project_budget: "Budget du Projet",
    submit_proposal: "Soumettre une Proposition",
    about_client: "À Propos du Client",
    client_name: "Nom du Client",
    industry: "Secteur d'Activité",
    website: "Site Web",
    member_since: "Membre Depuis",
    share_this_project: "Partager ce Projet",
    search_category: "Catégorie de Recherche",
    search_freelancers_placeholder: "Rechercher des freelances...",
    professionals: "professionnels",
    sort_by: "Trier par",
    sort_recommended: "Recommandé",
    sort_rate_high_low: "Tarif Horaire : Du + Élevé au - Élevé",
    sort_rate_low_high: "Tarif Horaire : Du - Élevé au + Élevé",
    home2_hero_title_prefix: "Transformez",
    home2_hero_title_highlight: "Votre Équipe avec",
    home2_hero_title_suffix: "La Découverte des Meilleurs Talents",
    home2_hero_subtitle: "Épanouissez-vous dans un écosystème freelance dynamique dédié à l'excellence et aux opportunités illimitées.",
    home2_search_placeholder: "Rechercher par mot-clé",
    home2_filter_label: "Vendeurs",
    home2_search_btn: "Rechercher",
    home2_popular_label: "Catégories populaires",
    home2_category_chips: "Marketing numérique, Analyse et Stratégie, Services IA",
    home2_cs_badge: "Meilleurs Plans à Choisir",
    home2_cs_title: "Conçu Avec Attention et Proche de Vos Besoins",
    home2_cs_subtitle: "Entrez dans un monde de possibilités illimitées, où les talents extraordinaires s'épanouissent.",
    testimonial_1_name: "Elena Rodriguez",
    testimonial_1_role: "CTO, TechStart Inc.",
    testimonial_1_quote: "Trouver le bon développeur pour notre plate-forme principale était difficile. Freelancer nous a mis en relation avec David en 24 heures. Son expertise a accéléré notre lancement de 2 mois.",
    testimonial_2_name: "Marcus Vance",
    testimonial_2_role: "Fondateur, Apex Systems",
    testimonial_2_quote: "Nous avions besoin d'une refonte complète de notre portail SaaS dans des délais serrés. Le designer trouvé par Freelancer était spectaculaire, livrant des prototypes Figma parfaits en avance.",
    testimonial_3_name: "Priya Patel",
    testimonial_3_role: "Responsable Produit, CloudScale",
    testimonial_3_quote: "L'ingénieur en automatisation de l'IA que nous avons embauché via Freelancer a intégré un pipeline LLM personnalisé dans notre produit en seulement deux semaines. Excellent vivier de talents.",
    profile_status: "Statut du profil",
    complete_percent: "{percent}% complété",
    complete_client_profile_desc: "Complétez votre profil client étape par étape",
    complete_freelancer_profile_desc: "Complétez votre profil de freelance étape par étape",
    client_profile_unlock_info: "Remplir les informations de base de votre entreprise, de votre présence en ligne et de votre contact de recrutement déverrouille les listes de talents.",
    freelancer_profile_unlock_info: "Remplir votre titre professionnel, votre historique d'expérience, vos études, vos certifications et vos compétences déverrouille les contrats de placement direct.",
    available_funds: "Fonds disponibles",
    active_virtual_balance: "Solde virtuel actif",
    workspace_metrics: "Mesures de l'espace de travail",
    dynamic_client_totals: "Totaux de compte client dynamique",
    dynamic_freelancer_totals: "Totaux de compte de freelance dynamique",
    total_expenditures: "Dépenses totales",
    posted_projects: "Projets affichés",
    purchased_gigs: "Services achetés",
    hired_partners: "Partenaires embauchés",
    net_earnings: "Gains nets",
    active_bids: "Offres actives",
    active_gigs_label: "Services actifs",
    gig_orders: "Commandes de services",
    active_contracts: "Contrats actifs",
    active_contracts_desc: "Contrats de projet actuels",
    budget_label: "Budget : ",
    no_active_contracts: "Aucun contrat actif",
    earning_history: "Historique des gains",
    earning_history_desc: "Libérations nettes de paiement séquestre groupées par mois civil",
    no_earnings_yet: "Pas encore de gains",
    submitted_bids: "Offres soumises",
    submitted_bids_desc: "Propositions et offres en attente",
    btn_view_all: "Voir tout",
    project_application: "Candidature au projet",
    no_submitted_bids: "Aucune offre soumise",
    orders_received: "Commandes reçues",
    orders_received_desc: "Livraisons de services en cours",
    active_service_delivery: "Livraison de service active",
    no_gig_orders_received: "Aucune commande de service reçue",
    inbox_messages_menu: "Messages reçus",
    new_badge: "Nouveau",
    my_wallet_menu: "Mon Portefeuille",
    financial_reports_menu: "Rapports financiers",
    subscription_menu: "Mon Abonnement",
    referrals_menu: "Parrainer et Gagner",
    affiliate_menu: "Portail d'Affiliation",
    settings_menu: "Paramètres",
    pending: "En attente",
    accepted: "Accepté",
    completed: "Terminé",
    rejected: "Refusé",
    cancelled: "Annulé",
    bid: "Offre",
    gig: "Service",
    order_hash: "Commande #",
    "under review": "En cours de révision",
    under_review: "En cours de révision",
    "work started": "Travail commencé",
    work_started: "Travail commencé",
    "in progress": "En cours",
    in_progress: "En cours",
    hired: "Embauché",
    "work completed": "Travail terminé",
    work_completed: "Travail terminé",
    disputed: "Contesté",
    project_milestone_delivery_title: "Étape et livraison du projet",
    gig_order_delivery_title: "Livraison de la commande de service",
    btn_back_to_dashboard: "Retour au tableau de bord",
    wishlist_saved_items: "Éléments enregistrés",
    wishlist_desc: "Gardez une trace des services, des projets et des freelances que vous souhaitez embaucher, avec lesquels vous souhaitez collaborer ou sur lesquels vous souhaitez soumissionner à l'avenir.",
    services_tab: "Services",
    projects_tab: "Projets",
    freelancers_tab: "Freelances",
    view_gig_btn: "Voir le service",
    no_saved_services: "Aucun service enregistré",
    no_saved_services_desc: "Parcurrez notre large variété de services d'experts et cliquez sur l'icône de cœur pour les enregistrer ici.",
    start_exploring_btn: "Commencer à explorer",
    no_saved_projects: "Aucun projet enregistré",
    no_saved_projects_desc: "Parcourez nos briefs de projets ouverts et cliquez sur l'icône de cœur pour les enregistrer ici.",
    no_saved_freelancers: "Aucun freelance enregistré",
    no_saved_freelancers_desc: "Trouvez des développeurs ou des designers d'élite et cliquez sur l'icône de cœur pour les enregistrer ici.",
    vetted_badge: "Vérifié",
    find_projects_header: "Trouver des projets et des offres",
    find_projects_desc: "Parcourez les projets actifs publiés par les clients et soumettez vos propositions.",
    search_jobs_placeholder: "Rechercher des emplois, des catégories...",
    show_all_btn: "Afficher tout",
    ai_matches_btn: "Correspondances IA",
    proposal_submitted_badge: "Proposition soumise",
    subcategory_label: "Sous-catégorie :",
    experience_required_label: "Expérience requise :",
    duration_label: "Durée :",
    freelancers_label: "Freelances :",
    submit_proposal_btn: "Soumettre une proposition",
    hours_limit_label: "Limite d'heures :",
    payout_label: "Paiement :",
    checking_btn: "Vérification...",
    my_submitted_proposals_header: "Mes propositions soumises",
    my_submitted_proposals_desc: "Suivez et gérez le statut de vos offres sur les projets clients actifs.",
    find_projects_btn_label: "Trouver des projets",
    total_submitted_metric: "Total soumis",
    accepted_offers_metric: "Offres acceptées",
    pending_review_metric: "En attente de révision",
    declined_metric: "Refusé",
    all_proposals_filter: "Toutes les propositions",
    pending_review_filter: "En attente de révision",
    accepted_hired_filter: "Accepté et embauché",
    declined_cancelled_filter: "Refusé et annulé",
    search_proposals_placeholder: "Rechercher des propositions...",
    direct_hire_offer: "Offre d'embauche directe",
    offer_invitation_msg: "Message d'invitation à l'offre",
    cover_letter_label: "Lettre de motivation",
    offer_budget_label: "Budget de l'offre :",
    delivery_time_label: "Délai de livraison :",
    accept_offer_btn: "Accepter l'offre",
    decline_btn: "Décliner",
    view_details_btn: "Voir les détails",
    proposals_label_pagination: "propositions",
    "awaiting payment": "En attente de paiement",
    client_prefix: "Client :",
    offer_date_prefix: "Date de l'offre :",
    my_projects_contracts_header: "Mes projets et contrats",
    my_projects_contracts_desc: "Gerez vos missions de freelance actives, suivez les etapes de realisation et consultez l'historique des clients.",
    ongoing_projects_filter: "Projets en cours",
    completed_projects_filter: "Projets terminés",
    cancelled_projects_filter: "Projets annulés",
    all_projects_filter: "Tous les projets",
    awaiting_approval_status: "En attente d'approbation",
    milestone_progress_label: "Progression des jalons",
    start_work_btn: "Commencer le travail",
    submit_completed_work_btn: "Soumettre le travail terminé",
    work_submitted_awaiting_approval_status: "Travail soumis / En attente d'approbation",
    hired_date_prefix: "Embauché :",
    my_clients_tab: "Mes clients",
    recommended_clients_tab: "Clients recommandés",
    no_client_history_yet: "Aucun historique client pour le moment",
    no_client_history_desc: "Terminez vos contrats actifs pour commencer à établir l'historique de votre liste de clients.",
    message_client_btn: "Contacter le client",
    no_client_recommendations: "Aucune recommandation client",
    no_client_recommendations_desc: "Aucun client recruteur actif correspondant aux recommandations pour le moment.",
    direct_hiring_client_label: "Client recruteur direct",
    view_client_profile_btn: "Voir le profil du client",
    back_to_projects_btn: "Retour aux projets",
    open_chat_btn: "Ouvrir le chat",
    hourly_rate_label: "Taux horaire",
    escrow_remaining_label: "Dépôt de garantie restant :",
    progress_label: "Progression",
    client_partner_label: "Client partenaire",
    contract_scope_desc_label: "Portée du contrat et description",
    service_orders_header: "Commandes de service",
    service_orders_desc: "Examinez les exigences de projet personnalisées et acceptez ou rejetez les commandes envoyées par les clients.",
    all_orders_tab: "Toutes les commandes",
    pending_filter_label: "En attente",
    active_filter_label: "Actif",
    completed_filter_label: "Terminé",
    no_all_orders_found: "Aucune commande trouvée",
    no_pending_orders_found: "Aucune commande en attente",
    no_active_orders_found: "Aucune commande active",
    no_completed_orders_found: "Aucune commande terminée",
    no_orders_matching_category_desc: "Vous n'avez aucune commande correspondant à cette catégorie actuellement.",
    conversations_sidebar_header: "Conversations",
    syncing_chats_label: "Synchronisation des discussions...",
    no_active_chats_title: "Aucune discussion active",
    no_active_chats_desc: "Vos conversations commencent automatiquement lorsqu'une proposition est acceptée !",
    select_chat_room_title: "Sélectionnez un salon de discussion",
    select_chat_room_desc: "Sélectionnez une conversation candidate dans la liste pour afficher les livrables et discuter des détails du projet.",
    dispute_system_update_msg: "⚠️ Mise à jour du système de litige",
    custom_payment_offer_received_msg: "📩 Offre de paiement personnalisée reçue",
    no_messages_yet_msg: "Aucun message pour l'instant. Dites bonjour !",
    custom_payment_offer_label: "Offre de paiement personnalisée",
    accept_offer_fund_escrow_btn: "Accepter l'offre et financer le dépôt de garantie",
    sent_waiting_client_approval_label: "Envoyé et en attente de l'approbation du client",
    offer_accepted_order_active_label: "Offre acceptée et commande active !",
    platform_notification_header: "Notification de la plateforme",
    system_notification_header: "Notification du système",
    you_label: "Vous",
    user_role_label: "Utilisateur",
    proposal_submitted_btn: "Proposition soumise",
    share_earn_btn: "Partager et gagner",
    best_match_label: "Meilleure correspondance",
    match_score_label: "Match",
    view_project_btn: "Voir le projet →",
    analysing_profile_status: "Analyse de votre profil...",
    ai_matching_skills_status: "L'IA associe vos compétences aux meilleurs projets ouverts",
    no_strong_matches_found: "Aucune correspondance solide trouvée",
    no_strong_matches_desc: "Essayez de compléter davantage votre profil de freelance afin que l'IA puisse mieux comprendre votre expertise.",
    saves: "sauvegardes",
    featured_label: "Meilleurs Talents",
    request_quote: "Demander un devis",
    global_trust_eyebrow: "Nous nous développons de jour en jour",
    global_trust_title: "Confiance mondiale d'un million d'entreprises et ce n'est pas fini",
    global_trust_desc: "Connectez-vous avec des professionnels qualifiés, simplifiez la collaboration et débloquez le succès. Rejoignez-nous maintenant et redéfinissez votre expérience de travail !",
    global_trust_check_1: "Connectez-vous avec des pros, collaborez mieux, réussissez plus vite",
    global_trust_check_2: "Redéfinissez le travail, inscrivez-vous maintenant pour une meilleure expérience",
    global_trust_check_3: "Simplifiez la collaboration, débloquez le succès",
    global_trust_check_4: "Rejoignez-nous, redéfinissez votre expérience de travail"
  },
  ES: {
    nav_categories: "Categorías",
    nav_talent: "Contratar Freelancers",
    nav_projects: "Buscar Proyectos",
    nav_gigs: "Explorar Servicios",
    nav_blogs: "Blogs",
    btn_back: "Volver",
    btn_send_message: "Enviar Mensaje",
    btn_hire_freelancer: "Contratar Freelance",
    btn_browse: "Explorar",
    btn_view_all_categories: "Ver todas las categorías",
    categories_title: "Explorar categorías populares",
    professional_bio: "Biografía Profesional",
    freelancer_metadata: "Detalles del Freelancer",
    core_competencies: "Competencias Principales",
    hourly_rate: "Tarifa por hora",
    exp_level: "Nivel de experiencia",
    active: "activo(s)",
    jobs: "trabajos",
    available_now: "Disponible ahora",
    currently_busy: "Ocupado actualmente",
    sign_in: "Iniciar sesión",
    get_started: "Comenzar",
    dashboard: "Panel de control",
    nav_view_profile: "Ver perfil",
    nav_logout: "Cerrar sesión",
    testimonial_1_name: "Elena Rodriguez",
    testimonial_1_role: "CTO, TechStart Inc.",
    testimonial_1_quote: "Encontrar al desarrollador adecuado para nuestra plataforma principal fue un desafío. Freelancer nos conectó con David en 24 horas. Su experiencia aceleró nuestro lanzamiento por 2 meses.",
    testimonial_2_name: "Marcus Vance",
    testimonial_2_role: "Fundador, Apex Systems",
    testimonial_2_quote: "Necesitábamos un rediseño completo de nuestro portal SaaS en un plazo ajustado. El diseñador que encontró Freelancer fue espectacular, entregando prototipos Figma perfectos antes de lo previsto.",
    testimonial_3_name: "Priya Patel",
    testimonial_3_role: "Líder de Producto, CloudScale",
    testimonial_3_quote: "El ingeniero de automatización de IA que contratamos a través de Freelancer integró un pipeline de LLM personalizado en nuestro producto en solo dos semanas. Excelente grupo de talentos.",
    profile_status: "Estado del perfil",
    complete_percent: "{percent}% completado",
    complete_client_profile_desc: "Complete su perfil de cliente paso a paso",
    complete_freelancer_profile_desc: "Complete su perfil de freelancer paso a paso",
    client_profile_unlock_info: "Completar los aspectos básicos de su empresa, los detalles de presencia en la web y la información de contacto de contratación desbloquea listas de talentos.",
    freelancer_profile_unlock_info: "Completar su título profesional, historial de experiencia, educación, certificaciones y habilidades desbloquea contratos de colocación directa.",
    available_funds: "Fondos disponibles",
    active_virtual_balance: "Saldo virtual activo",
    workspace_metrics: "Métricas del espacio de trabajo",
    dynamic_client_totals: "Totales de cuenta de cliente dinámicos",
    dynamic_freelancer_totals: "Totales de cuenta de freelancer dinámicos",
    total_expenditures: "Gastos totales",
    posted_projects: "Proyectos publicados",
    purchased_gigs: "Servicios comprados",
    hired_partners: "Socios contratados",
    net_earnings: "Ganancias netas",
    active_bids: "Ofertas activas",
    active_gigs_label: "Servicios activos",
    gig_orders: "Pedidos de servicios",
    active_contracts: "Contratos activos",
    active_contracts_desc: "Contratos de proyectos actuales",
    budget_label: "Presupuesto: ",
    no_active_contracts: "Sin contratos activos",
    earning_history: "Historial de ganancias",
    earning_history_desc: "Liberaciones de pago de depósito en garantía neto agrupadas por mes calendario",
    no_earnings_yet: "Aún no hay ganancias",
    submitted_bids: "Ofertas presentadas",
    submitted_bids_desc: "Propuestas y ofertas pendientes",
    btn_view_all: "Ver todo",
    project_application: "Solicitud de proyecto",
    no_submitted_bids: "No hay ofertas presentadas",
    orders_received: "Pedidos recibidos",
    orders_received_desc: "Entregas de servicios en curso",
    active_service_delivery: "Entrega de servicio activa",
    no_gig_orders_received: "No se recibieron pedidos de servicios",
    inbox_messages_menu: "Mensajes de buzón",
    new_badge: "Nuevo",
    my_wallet_menu: "Mi Billetera",
    financial_reports_menu: "Informes financieros",
    subscription_menu: "Mi Suscripción",
    referrals_menu: "Recomendar y Ganar",
    affiliate_menu: "Portal de Afiliados",
    settings_menu: "Configuración",
    pending: "Pendiente",
    accepted: "Aceptado",
    completed: "Completado",
    rejected: "Rechazado",
    cancelled: "Cancelado",
    bid: "Oferta",
    gig: "Servicio",
    order_hash: "Pedido #",
    "under review": "En revisión",
    under_review: "En revisión",
    "work started": "Trabajo iniciado",
    work_started: "Trabajo iniciado",
    "in progress": "En progreso",
    in_progress: "En progreso",
    hired: "Contratado",
    "work completed": "Trabajo completado",
    work_completed: "Trabajo completado",
    disputed: "En disputa",
    project_milestone_delivery_title: "Hito y entrega del proyecto",
    gig_order_delivery_title: "Entrega del pedido de servicio",
    btn_back_to_dashboard: "Volver al panel de control",
    wishlist_saved_items: "Artículos guardados",
    wishlist_desc: "Realice un seguimiento de los servicios, proyectos y freelancers que desea contratar, con los que desea colaborar o por los que desea ofertar en el futuro.",
    services_tab: "Servicios",
    projects_tab: "Proyectos",
    freelancers_tab: "Freelancers",
    view_gig_btn: "Ver servicio",
    no_saved_services: "No hay servicios guardados",
    no_saved_services_desc: "Explore nuestra amplia variedad de servicios de expertos y haga clic en el icono del corazón para guardarlos aquí.",
    start_exploring_btn: "Comenzar a explorar",
    no_saved_projects: "No hay proyectos guardados",
    no_saved_projects_desc: "Explore nuestros resúmenes de proyectos abiertos y haga clic en el icono del corazón para guardarlos aquí.",
    no_saved_freelancers: "No hay freelancers guardados",
    no_saved_freelancers_desc: "Encuentre desarrolladores o diseñadores de élite y haga clic en el icono del corazón para guardarlos aquí.",
    vetted_badge: "Verificado",
    find_projects_header: "Buscar proyectos y ofertas",
    find_projects_desc: "Explore proyectos activos publicados por clientes y envíe sus propuestas.",
    search_jobs_placeholder: "Buscar trabajos, categorías...",
    show_all_btn: "Mostrar todo",
    ai_matches_btn: "Coincidencias de IA",
    proposal_submitted_badge: "Propuesta enviada",
    subcategory_label: "Subcategoría:",
    experience_required_label: "Experiencia requerida:",
    duration_label: "Duración:",
    freelancers_label: "Freelancers:",
    submit_proposal_btn: "Presentar propuesta",
    hours_limit_label: "Límite de horas:",
    payout_label: "Pago:",
    checking_btn: "Comprobando...",
    my_submitted_proposals_header: "Mis propuestas enviadas",
    my_submitted_proposals_desc: "Realice un seguimiento y gestione el estado de sus ofertas en proyectos de clientes activos.",
    find_projects_btn_label: "Buscar proyectos",
    total_submitted_metric: "Total enviado",
    accepted_offers_metric: "Ofertas aceptadas",
    pending_review_metric: "En revisión",
    declined_metric: "Rechazado",
    all_proposals_filter: "Todas las propuestas",
    pending_review_filter: "En revisión",
    accepted_hired_filter: "Aceptado y contratado",
    declined_cancelled_filter: "Rechazado y cancelado",
    search_proposals_placeholder: "Buscar propuestas...",
    direct_hire_offer: "Oferta de contratación directa",
    offer_invitation_msg: "Mensaje de invitación a la oferta",
    cover_letter_label: "Carta de presentación",
    offer_budget_label: "Presupuesto de la oferta:",
    delivery_time_label: "Plazo de entrega:",
    accept_offer_btn: "Aceptar oferta",
    decline_btn: "Rechazar",
    view_details_btn: "Ver detalles",
    proposals_label_pagination: "propuestas",
    "awaiting payment": "Esperando pago",
    client_prefix: "Cliente:",
    offer_date_prefix: "Fecha de la oferta:",
    my_projects_contracts_header: "Mis proyectos y contratos",
    my_projects_contracts_desc: "Gestione sus asignaciones activas de freelancer, realice un seguimiento de los hitos de finalización y vea el historial de clientes.",
    ongoing_projects_filter: "Proyectos en curso",
    completed_projects_filter: "Proyectos completados",
    cancelled_projects_filter: "Proyectos cancelados",
    all_projects_filter: "Todos los proyectos",
    awaiting_approval_status: "Esperando aprobación",
    milestone_progress_label: "Progreso de hitos",
    start_work_btn: "Comenzar trabajo",
    submit_completed_work_btn: "Presentar trabajo completado",
    work_submitted_awaiting_approval_status: "Trabajo presentado / Esperando aprobación",
    hired_date_prefix: "Contratado:",
    my_clients_tab: "Mis clientes",
    recommended_clients_tab: "Clientes recomendados",
    no_client_history_yet: "Aún no hay historial de clientes",
    no_client_history_desc: "Complete sus contratos activos para comenzar a crear el historial de la lista de clientes.",
    message_client_btn: "Enviar mensaje al cliente",
    no_client_recommendations: "No hay recomendaciones de clientes",
    no_client_recommendations_desc: "No se encontraron clientes contratantes activos que se ajusten a las recomendaciones en este momento.",
    direct_hiring_client_label: "Cliente de contratación directa",
    view_client_profile_btn: "Ver perfil del cliente",
    back_to_projects_btn: "Volver a los proyectos",
    open_chat_btn: "Abrir chat",
    hourly_rate_label: "Tarifa por hora",
    escrow_remaining_label: "Garantía restante:",
    progress_label: "Progreso",
    client_partner_label: "Cliente socio",
    contract_scope_desc_label: "Alcance del contrato y descripción",
    service_orders_header: "Pedidos de servicio",
    service_orders_desc: "Revise los requisitos del proyecto personalizados y acepte o rechace los pedidos enviados por los clientes.",
    all_orders_tab: "Todos los pedidos",
    pending_filter_label: "Pendiente",
    active_filter_label: "Activo",
    completed_filter_label: "Completado",
    no_all_orders_found: "No se encontraron pedidos",
    no_pending_orders_found: "No se encontraron pedidos pendientes",
    no_active_orders_found: "No se encontraron pedidos activos",
    no_completed_orders_found: "No se encontraron pedidos completados",
    no_orders_matching_category_desc: "No tiene ningún pedido que coincida con esta categoría actualmente.",
    conversations_sidebar_header: "Conversaciones",
    syncing_chats_label: "Sincronizando chats...",
    no_active_chats_title: "No hay chats activos",
    no_active_chats_desc: "¡Sus conversaciones comienzan automáticamente cuando se acepta una propuesta!",
    select_chat_room_title: "Seleccione una sala de chat",
    select_chat_room_desc: "Seleccione una conversación de candidato de la lista para ver los entregables y discutir los detalles del proyecto.",
    dispute_system_update_msg: "⚠️ Actualización del sistema de disputas",
    custom_payment_offer_received_msg: "📩 Oferta de pago personalizada recibida",
    no_messages_yet_msg: "Aún no hay mensajes. ¡Diga hola!",
    custom_payment_offer_label: "Oferta de pago personalizada",
    accept_offer_fund_escrow_btn: "Aceptar oferta y financiar garantía",
    sent_waiting_client_approval_label: "Enviado y esperando la aprobación del cliente",
    offer_accepted_order_active_label: "¡Oferta aceptada y pedido activo!",
    platform_notification_header: "Notificación de la plataforma",
    system_notification_header: "Notificación del sistema",
    you_label: "Tú",
    user_role_label: "Usuario",
    proposal_submitted_btn: "Propuesta presentada",
    share_earn_btn: "Compartir y ganar",
    best_match_label: "Mejor coincidencia",
    match_score_label: "Coincidencia",
    view_project_btn: "Ver proyecto →",
    analysing_profile_status: "Analizando su perfil...",
    ai_matching_skills_status: "La IA está emparejando sus habilidades con los mejores proyectos abiertos",
    no_strong_matches_found: "No se encontraron coincidencias sólidas",
    no_strong_matches_desc: "Intente completar más su perfil de freelancer para que la IA pueda comprender mejor su experiencia.",
    saves: "guardados",
    featured_label: "Mejores Talentos",
    request_quote: "Solicitar cotización",
    global_trust_eyebrow: "Nos expandimos día a día",
    global_trust_title: "Confianza global de 1 millón de empresas y contando",
    global_trust_desc: "Conéctese con profesionales capacitados, optimice la colaboración y libere el éxito. ¡Únase ahora y redefina su experiencia laboral!",
    global_trust_check_1: "Conéctese con profesionales, colabore mejor, tenga éxito más rápido",
    global_trust_check_2: "Redefina el trabajo, únase ahora para una mejor experiencia",
    global_trust_check_3: "Optimice la colaboración, libere el éxito",
    global_trust_check_4: "Únase a nosotros, redefina su experiencia laboral"
  },
  AR: {
    nav_categories: "الفئات",
    nav_talent: "توظيف مستقلين",
    nav_projects: "البحث عن مشاريع",
    nav_gigs: "استكشاف الخدمات",
    nav_blogs: "المدونات",
    btn_back: "رجوع",
    btn_send_message: "إرسال رسالة",
    btn_hire_freelancer: "توظيف المستقل",
    btn_browse: "تصفح",
    btn_view_all_categories: "عرض جميع الفئات",
    categories_title: "تصفح الفئات الشائعة",
    professional_bio: "السيرة الذاتية المهنية",
    freelancer_metadata: "بيانات المستقل",
    core_competencies: "المهارات الأساسية",
    hourly_rate: "الأجر بالساعة",
    exp_level: "مستوى الخبرة",
    active: "نشط",
    jobs: "وظائف",
    available_now: "متاح الآن",
    currently_busy: "مشغول حالياً",
    sign_in: "تسجيل الدخول",
    get_started: "ابدأ الآن",
    dashboard: "لوحة التحكم",
    nav_view_profile: "عرض الملف الشخصي",
    nav_logout: "تسجيل الخروج",
    logout_btn: "تسجيل الخروج",
    explore_top_freelancers: "استكشف أفضل المستقلين",
    explore_top_freelancers_desc: "راجع أوراق الاعتماد والمهارات وتقييمات العملاء لاختيار الأنسب.",
    search_skills_placeholder: "البحث في المهارات، الأسماء، الأدوار...",
    per_hour: "/ساعة",
    btn_view_profile: "عرض الملف الشخصي",
    no_bio_provided: "لم يتم توفير سيرة ذاتية مهنية بعد من قبل هذا المستقل.",
    no_matches_found: "لم يتم العثور على نتائج مطابقة",
    no_matches_found_desc: "اضبط مصطلح البحث أو معلمات التصفية.",
    already_hired_freelancers: "المستقلون الذين تم توظيفهم بالفعل",
    hired_freelancers_desc: "تتبع المستقلين الذين قمت بتوظيفهم والاتصال بهم وعرض التزاماتهم النشطة.",
    loading_hired_freelancers: "جاري تحميل المستقلين الموظفين...",
    no_freelancers_hired_yet: "لم يتم توظيف مستقلين بعد",
    no_freelancers_hired_yet_desc: "ابدأ التوظيف من خلال تصفح المواهب الموصى بها أو نشر مشروع.",
    btn_browse_talent: "تصفح المواهب",
    btn_post_project: "نشر مشروع",
    elite_developer: "مطور نخبة",
    hired_contract_partner_bio: "شريك عقد موظف نشط في لوحة التحكم الخاصة بك.",
    engagements_with_you: "التعاقدات معك",
    total: "إجمالي",
    more_click_profile_all: "المزيد · انقر فوق الملف الشخصي لعرض الكل",
    no_active_engagements: "لم يتم العثور على تعاقدات نشطة.",
    home_variations: "تنوعات الصفحة الرئيسية",
    home_1_default: "الصفحة الرئيسية 1 (افتراضي)",
    home_2: "الصفحة الرئيسية 2",
    home_3: "الصفحة الرئيسية 3",
    testimonial_1_name: "إيلينا رودريغيز",
    testimonial_1_role: "المدير التكنولوجي التنفيذي، شركة تيك ستارت",
    testimonial_1_quote: "كان العثور على المطور المناسب لمنصتنا الأساسية أمراً شاقاً. قام مستقل بجمعنا مع ديفيد في غضون 24 ساعة. ساهمت خبرته في تسريع إطلاقنا لمدة شهرين.",
    testimonial_2_name: "ماركوس فانس",
    testimonial_2_role: "مؤسس، أبكس سيستمز",
    testimonial_2_quote: "كنا بحاجة إلى إعادة تصميم كاملة لبوابة الخدمة الخاصة بنا تحت موعد نهائي ضيق. المصمم الذي عثرنا عليه عبر مستقل كان مذهلاً - حيث قدم نماذج فيجما مثالية قبل الموعد المحدد.",
    testimonial_3_name: "بريا باتيل",
    testimonial_3_role: "رئيس المنتج، كلاود سكيل",
    testimonial_3_quote: "مهندس أتمتة الذكاء الاصطناعي الذي قمنا بتوظيفه من خلال مستقل قام بدمج خط أنابيب مخصص لنماذج اللغة الكبيرة في منتجنا خلال أسبوعين فقط. مواهب متميزة ومدفوعات سلسة.",
    profile_status: "حالة الملف الشخصي",
    complete_percent: "مكتمل بنسبة {percent}%",
    complete_client_profile_desc: "أكمل ملف تعريف العميل الخاص بك خطوة بخطوة",
    complete_freelancer_profile_desc: "أكمل ملف تعريف المستقل الخاص بك خطوة بخطوة",
    client_profile_unlock_info: "يؤدي ملء أساسيات شركتك وتفاصيل تواجدك على الويب ومعلومات الاتصال بالتوظيف إلى فتح قوائم المواهب عن بُعد.",
    freelancer_profile_unlock_info: "يؤدي ملء لقبك المهني وسجل خبرتك وتعليمك وشهاداتك ومهاراتك إلى فتح عقود توظيف مباشرة.",
    available_funds: "الأموال المتاحة",
    active_virtual_balance: "الرصيد الافتراضي النشط",
    workspace_metrics: "مقاييس مساحة العمل",
    dynamic_client_totals: "إجمالي حساب العميل الديناميكي",
    dynamic_freelancer_totals: "إجمالي حساب المستقل الديناميكي",
    total_expenditures: "إجمالي النفقات",
    posted_projects: "المشاريع المنشورة",
    purchased_gigs: "الخدمات المشتراة",
    hired_partners: "الشركاء الموظفون",
    net_earnings: "صافي الأرباح",
    active_bids: "العروض النشطة",
    active_gigs_label: "الخدمات النشطة",
    gig_orders: "طلبات الخدمات",
    active_contracts: "العقود النشطة",
    active_contracts_desc: "عقود المشاريع الحالية",
    budget_label: "الميزانية: ",
    no_active_contracts: "لا توجد عقود نشطة",
    earning_history: "سجل الأرباح",
    earning_history_desc: "صافي إصدارات دفع الضمان مجمعة حسب الشهر التقويمي",
    no_earnings_yet: "لا توجد أرباح بعد",
    submitted_bids: "العروض المقدمة",
    submitted_bids_desc: "المقترحات والعروض المعلقة",
    btn_view_all: "عرض الكل",
    project_application: "طلب مشروع",
    no_submitted_bids: "لا توجد عروض مقدمة",
    orders_received: "الطلبات المستلمة",
    orders_received_desc: "تسليم الخدمات المستمرة",
    active_service_delivery: "تسليم خدمة نشط",
    no_gig_orders_received: "لم يتم استلام طلبات خدمات",
    inbox_messages_menu: "رسائل البريد الوارد",
    new_badge: "جديد",
    my_wallet_menu: "محفظتي",
    financial_reports_menu: "التقارير المالية",
    subscription_menu: "اشتراكي",
    referrals_menu: "الإحالة والكسب",
    affiliate_menu: "بوابة الشركاء",
    settings_menu: "الإعدادات",
    pending: "معلق",
    accepted: "مقبول",
    completed: "مكتمل",
    rejected: "مرفوض",
    cancelled: "ملغي",
    bid: "عرض",
    gig: "خدمة",
    order_hash: "طلب رقم #",
    "under review": "قيد المراجعة",
    under_review: "قيد المراجعة",
    "work started": "بدأ العمل",
    work_started: "بدأ العمل",
    "in progress": "قيد التنفيذ",
    in_progress: "قيد التنفيذ",
    hired: "تم التوظيف",
    "work completed": "تم إكمال العمل",
    work_completed: "تم إكمال العمل",
    disputed: "متنازع عليه",
    project_milestone_delivery_title: "معلم المشروع والتسليم",
    gig_order_delivery_title: "تسليم طلب الخدمة",
    btn_back_to_dashboard: "العودة إلى لوحة التحكم",
    wishlist_saved_items: "العناصر المحفوظة",
    wishlist_desc: "تتبع الخدمات والمشاريع والمستقلين الذين ترغب في توظيفهم أو التعاون معهم أو تقديم عروض أسعار لهم في المستقبل.",
    services_tab: "الخدمات",
    projects_tab: "المشاريع",
    freelancers_tab: "المستقلين",
    view_gig_btn: "عرض الخدمة",
    no_saved_services: "لا توجد خدمات محفوظة",
    no_saved_services_desc: "تصفح مجموعتنا الواسعة من الخدمات المتخصصة وانقر على أيقونة القلب لحفظها هنا.",
    start_exploring_btn: "ابدأ الاستكشاف",
    no_saved_projects: "لا توجد مشاريع محفوظة",
    no_saved_projects_desc: "تصفح موجزات المشاريع المفتوحة لدينا وانقر على أيقونة القلب لحفظها هنا.",
    no_saved_freelancers: "لا يوجد مستقلون محفوظون",
    no_saved_freelancers_desc: "ابحث عن المطورين أو المصممين النخبة وانقر على أيقونة القلب لحفظهم هنا.",
    vetted_badge: "موثق",
    find_projects_header: "البحث عن المشاريع والعروض",
    find_projects_desc: "تصفح المشاريع النشطة التي نشرها العملاء وقدم مقترحاتك.",
    search_jobs_placeholder: "البحث عن وظائف، فئات...",
    show_all_btn: "عرض الكل",
    ai_matches_btn: "مطابقات الذكاء الاصطناعي",
    proposal_submitted_badge: "تم تقديم المقترح",
    subcategory_label: "الفئة الفرعية:",
    experience_required_label: "الخبرة المطلوبة:",
    duration_label: "المدة:",
    freelancers_label: "المستقلين:",
    submit_proposal_btn: "تقديم مقترح",
    hours_limit_label: "حد الساعات:",
    payout_label: "الدفع:",
    checking_btn: "جاري التحقق...",
    my_submitted_proposals_header: "مقترحاتي المقدمة",
    my_submitted_proposals_desc: "تتبع وإدارة حالة عروض الأسعار الخاصة بك في مشاريع العملاء النشطة.",
    find_projects_btn_label: "البحث عن مشاريع",
    total_submitted_metric: "إجمالي المقدمة",
    accepted_offers_metric: "العروض المقبولة",
    pending_review_metric: "قيد المراجعة",
    declined_metric: "مرفوض",
    all_proposals_filter: "كل المقترحات",
    pending_review_filter: "قيد المراجعة",
    accepted_hired_filter: "مقبول وموظف",
    declined_cancelled_filter: "مرفوض وملغي",
    search_proposals_placeholder: "البحث عن المقترحات...",
    direct_hire_offer: "عرض توظيف مباشر",
    offer_invitation_msg: "رسالة دعوة العرض",
    cover_letter_label: "رسالة التغطية",
    offer_budget_label: "ميزانية العرض:",
    delivery_time_label: "وقت التسليم:",
    accept_offer_btn: "قبول العرض",
    decline_btn: "رفض",
    view_details_btn: "عرض التفاصيل",
    proposals_label_pagination: "مقترحات",
    "awaiting payment": "في انتظار الدفع",
    client_prefix: "العميل:",
    offer_date_prefix: "تاريخ العرض:",
    my_projects_contracts_header: "مشاريعي وعقودي",
    my_projects_contracts_desc: "إدارة مهام العمل الحر النشطة، وتتبع معالم الإنجاز، وعرض سجل العملاء.",
    ongoing_projects_filter: "المشاريع الجارية",
    completed_projects_filter: "المشاريع المكتملة",
    cancelled_projects_filter: "المشاريع الملغاة",
    all_projects_filter: "كل المشاريع",
    awaiting_approval_status: "بانتظار الموافقة",
    milestone_progress_label: "تقدم المعالم",
    start_work_btn: "بدء العمل",
    submit_completed_work_btn: "تقديم العمل المكتمل",
    work_submitted_awaiting_approval_status: "تم تقديم العمل / بانتظار الموافقة",
    hired_date_prefix: "تم التوظيف:",
    my_clients_tab: "عملائي",
    recommended_clients_tab: "العملاء الموصى بهم",
    no_client_history_yet: "لا يوجد سجل للعملاء بعد",
    no_client_history_desc: "أكمل عقودك النشطة لبدء بناء سجل قائمة العملاء.",
    message_client_btn: "مراسلة العميل",
    no_client_recommendations: "لا توجد توصيات للعملاء",
    no_client_recommendations_desc: "لم يتم العثور على عملاء توظيف نشطين يناسبون التوصيات في الوقت الحالي.",
    direct_hiring_client_label: "عميل توظيف مباشر",
    view_client_profile_btn: "عرض ملف العميل",
    back_to_projects_btn: "العودة إلى المشاريع",
    open_chat_btn: "فتح الدردشة",
    hourly_rate_label: "أجر الساعة",
    escrow_remaining_label: "الضمان المتبقي:",
    progress_label: "التقدم",
    client_partner_label: "العميل الشريك",
    contract_scope_desc_label: "نطاق العقد والوصف",
    service_orders_header: "طلبات الخدمات",
    service_orders_desc: "مراجعة متطلبات المشروع المخصصة وقبول أو رفض الطلبات المرسلة من قبل العملاء.",
    all_orders_tab: "كل الطلبات",
    pending_filter_label: "قيد الانتظار",
    active_filter_label: "نشط",
    completed_filter_label: "مكتمل",
    no_all_orders_found: "لم يتم العثور على طلبات",
    no_pending_orders_found: "لم يتم العثور على طلبات معلقة",
    no_active_orders_found: "لم يتم العثور على طلبات نشطة",
    no_completed_orders_found: "لم يتم العثور على طلبات مكتملة",
    no_orders_matching_category_desc: "ليس لديك أي طلبات تطابق هذه الفئة حاليًا.",
    conversations_sidebar_header: "المحادثات",
    syncing_chats_label: "مزامنة المحادثات...",
    no_active_chats_title: "لا توجد محادثات نشطة",
    no_active_chats_desc: "تبدأ محادثاتك تلقائيًا عند قبول الاقتراح!",
    select_chat_room_title: "اختر غرفة دردشة",
    select_chat_room_desc: "اختر محادثة مرشحة من القائمة لعرض المخرجات ومناقشة تفاصيل المشروع.",
    dispute_system_update_msg: "⚠️ تحديث نظام النزاع",
    custom_payment_offer_received_msg: "📩 تم استلام عرض دفع مخصص",
    no_messages_yet_msg: "لا توجد رسائل بعد. قل مرحبًا!",
    custom_payment_offer_label: "عرض دفع مخصص",
    accept_offer_fund_escrow_btn: "قبول العرض وتمويل الضمان",
    sent_waiting_client_approval_label: "تم الإرسال وبانتظار موافقة العميل",
    offer_accepted_order_active_label: "تم قبول العرض والطلب نشط!",
    platform_notification_header: "إشعار المنصة",
    system_notification_header: "إشعار النظام",
    you_label: "أنت",
    user_role_label: "المستخدم",
    proposal_submitted_btn: "تم تقديم المقترح",
    share_earn_btn: "شارك واكسب",
    best_match_label: "أفضل تطابق",
    match_score_label: "تطابق",
    view_project_btn: "عرض المشروع ←",
    analysing_profile_status: "جاري تحليل ملفك الشخصي...",
    ai_matching_skills_status: "يقوم الذكاء الاصطناعي بمطابقة مهاراتك مع أفضل المشاريع المفتوحة",
    no_strong_matches_found: "لم يتم العثور على مطابقات قوية",
    no_strong_matches_desc: "حاول إكمال المزيد من ملفك الشخصي كمستقل حتى يتمكن الذكاء الاصطناعي من فهم خبرتك بشكل أفضل.",
    saves: "مرات الحفظ",
    featured_label: "مستقلون مميزون",
    request_quote: "طلب عرض سعر",
    global_trust_eyebrow: "نحن نتوسع يومًا بعد يوم",
    global_trust_title: "الثقة العالمية لمليون شركة والعدد في ازدياد",
    global_trust_desc: "تواصل مع مهنيين مهرة، وسهّل التعاون، وافتح أبواب النجاح. انضم الآن وأعد تعريف تجربة عملك!",
    global_trust_check_1: "تواصل مع المحترفين، وتعاون بشكل أفضل، وانجح بشكل أسرع",
    global_trust_check_2: "أعد تعريف العمل، وانضم الآن للحصول على تجربة أفضل",
    global_trust_check_3: "سهّل التعاون وافتح أبواب النجاح",
    global_trust_check_4: "انضم إلينا وأعد تعريف تجربة عملك"
  },
  DE: {
    nav_categories: "Kategorien",
    nav_talent: "Freelancer anheuern",
    nav_projects: "Projekte finden",
    nav_gigs: "Services erkunden",
    nav_blogs: "Blogs",
    btn_back: "Zurück",
    btn_send_message: "Nachricht senden",
    btn_hire_freelancer: "Freelancer buchen",
    btn_browse: "Durchsuchen",
    btn_view_all_categories: "Alle Kategorien anzeigen",
    categories_title: "Beliebte Kategorien durchsuchen",
    professional_bio: "Berufliches Profil",
    freelancer_metadata: "Freelancer-Informationen",
    core_competencies: "Kernkompetenzen",
    hourly_rate: "Stundensatz",
    exp_level: "Erfahrungsstufe",
    active: "aktiv",
    jobs: "Projekte",
    available_now: "Jetzt verfügbar",
    currently_busy: "Zurzeit beschäftigt",
    sign_in: "Einloggen",
    get_started: "Loslegen",
    dashboard: "Dashboard",
    nav_view_profile: "Profil anzeigen",
    nav_logout: "Abmelden",
    logout_btn: "Abmelden",
    explore_top_freelancers: "Top-Freelancer erkunden",
    explore_top_freelancers_desc: "Bewerten Sie Qualifikationen, Fähigkeiten und Kundenbewertungen.",
    search_skills_placeholder: "Suchen Sie nach Fähigkeiten, Namen, Rollen...",
    per_hour: "/Std.",
    btn_view_profile: "Profil anzeigen",
    no_bio_provided: "Dieser Freelancer hat noch keine Biografie angegeben.",
    no_matches_found: "Keine Übereinstimmungen gefunden",
    no_matches_found_desc: "Passen Sie Ihren Suchbegriff oder Ihre Filter an.",
    already_hired_freelancers: "Bereits eingestellte Freelancer",
    hired_freelancers_desc: "Verfolgen, kontaktieren und sehen Sie sich die aktiven Engagements der von Ihnen eingestellten Freelancer an.",
    loading_hired_freelancers: "Eingestellte Freelancer werden geladen...",
    no_freelancers_hired_yet: "Noch keine Freelancer eingestellt",
    no_freelancers_hired_yet_desc: "Beginnen Sie mit der Einstellung, indem Sie nach empfohlenen Talenten suchen oder ein Projekt veröffentlichen.",
    btn_browse_talent: "Talente durchsuchen",
    btn_post_project: "Projekt veröffentlichen",
    elite_developer: "Elite-Entwickler",
    hired_contract_partner_bio: "Aktiver eingestellter Vertragspartner auf Ihrem Dashboard.",
    engagements_with_you: "Engagements mit Ihnen",
    total: "insgesamt",
    more_click_profile_all: "mehr · Klicken Sie auf das Profil, um alle anzuzeigen",
    no_active_engagements: "Keine aktiven Engagements gefunden.",
    home_variations: "Homepage-Variationen",
    home_1_default: "Homepage 1 (Standard)",
    home_2: "Homepage 2",
    home_3: "Homepage 3",
    testimonial_1_name: "Elena Rodriguez",
    testimonial_1_role: "CTO, TechStart Inc.",
    testimonial_1_quote: "Den richtigen Entwickler für unsere Kernplattform zu finden, war eine Herausforderung. Freelancer hat uns innerhalb von 24 Stunden mit David zusammengebracht. Seine Expertise hat unseren Start um 2 Monate beschleunigt.",
    testimonial_2_name: "Marcus Vance",
    testimonial_2_role: "Gründer, Apex Systems",
    testimonial_2_quote: "Wir benötigten ein komplettes Redesign unseres SaaS-Portals unter engem Zeitdruck. Der von Freelancer gefundene Designer war spektakulär und lieferte pixelgenaue Figma-Prototypen vor dem Zeitplan.",
    testimonial_3_name: "Priya Patel",
    testimonial_3_role: "Product Lead, CloudScale",
    testimonial_3_quote: "Der AI Automation Engineer, den wir über Freelancer eingestellt haben, hat in nur zwei Wochen eine benutzerdefinierte LLM-Pipeline in unser Produkt integriert. Hervorragender Talentpool und nahtlose Zahlungen.",
    profile_status: "Profilstatus",
    complete_percent: "{percent}% vollständig",
    complete_client_profile_desc: "Vervollständigen Sie Ihr Kundenprofil Schritt für Schritt",
    complete_freelancer_profile_desc: "Vervollständigen Sie Ihr Freelancer-Profil Schritt für Schritt",
    client_profile_unlock_info: "Das Ausfüllen Ihrer Unternehmensgrundlagen, Webpräsenz-Details und Einstellungsansprechpartner-Infos schaltet Remote-Talentlisten frei.",
    freelancer_profile_unlock_info: "Das Ausfüllen Ihres Berufstitels, Ihres Erfahrungsverlaufs, Ihrer Ausbildung, Zertifizierungen und Fähigkeiten schaltet direkte Arbeitsvermittlungsverträge frei.",
    available_funds: "Verfügbare Mittel",
    active_virtual_balance: "Aktives virtuelles Guthaben",
    workspace_metrics: "Workspace-Metriken",
    dynamic_client_totals: "Dynamische Kundenkontostände",
    dynamic_freelancer_totals: "Dynamische Freelancer-Kontostände",
    total_expenditures: "Gesamtausgaben",
    posted_projects: "Gepostete Projekte",
    purchased_gigs: "Gekaufte Gigs",
    hired_partners: "Eingestellte Partner",
    net_earnings: "Nettoverdienst",
    active_bids: "Aktive Gebote",
    active_gigs_label: "Aktive Gigs",
    gig_orders: "Gig-Aufträge",
    active_contracts: "Aktive Verträge",
    active_contracts_desc: "Aktuelle Projektverträge",
    budget_label: "Budget: ",
    no_active_contracts: "Keine aktiven Verträge",
    earning_history: "Verdiensthistorie",
    earning_history_desc: "Netto-Treuhandauszahlungen gruppiert nach Kalendermonat",
    no_earnings_yet: "Noch keine Einnahmen",
    submitted_bids: "Abgegebene Gebote",
    submitted_bids_desc: "Ausstehende Vorschläge & Gebote",
    btn_view_all: "Alle anzeigen",
    project_application: "Projektbewerbung",
    no_submitted_bids: "Keine abgegebenen Gebote",
    orders_received: "Erhaltene Bestellungen",
    orders_received_desc: "Laufende Service-Lieferungen",
    active_service_delivery: "Aktive Service-Lieferung",
    no_gig_orders_received: "Keine Gig-Aufträge erhalten",
    inbox_messages_menu: "Posteingangsnachrichten",
    new_badge: "Neu",
    my_wallet_menu: "Mein Wallet",
    financial_reports_menu: "Finanzberichte",
    subscription_menu: "Mein Abonnement",
    referrals_menu: "Empfehlen & Verdienen",
    affiliate_menu: "Affiliate-Portal",
    settings_menu: "Einstellungen",
    pending: "Ausstehend",
    accepted: "Akzeptiert",
    completed: "Abgeschlossen",
    rejected: "Abgelehnt",
    cancelled: "Storniert",
    bid: "Gebot",
    gig: "Gig",
    order_hash: "Bestellung #",
    "under review": "Unter Überprüfung",
    under_review: "Unter Überprüfung",
    "work started": "Arbeit begonnen",
    work_started: "Arbeit begonnen",
    "in progress": "In Bearbeitung",
    in_progress: "In Bearbeitung",
    hired: "Eingestellt",
    "work completed": "Arbeit abgeschlossen",
    work_completed: "Arbeit abgeschlossen",
    disputed: "Umstritten",
    project_milestone_delivery_title: "Projekt-Meilenstein & Lieferung",
    gig_order_delivery_title: "Gig-Bestelllieferung",
    btn_back_to_dashboard: "Zurück zum Dashboard",
    wishlist_saved_items: "Gespeicherte Elemente",
    wishlist_desc: "Behalten Sie den Überblick über Dienstleistungen, Projekte und Freelancer, die Sie in Zukunft einstellen, mit denen Sie zusammenarbeiten oder auf die Sie bieten möchten.",
    services_tab: "Services",
    projects_tab: "Projekte",
    freelancers_tab: "Freelancer",
    view_gig_btn: "Gig anzeigen",
    no_saved_services: "Keine gespeicherten Gigs",
    no_saved_services_desc: "Durchsuchen Sie unsere große Auswahl an Experten-Gigs und klicken Sie auf das Herz-Symbol, um sie hier zu speichern.",
    start_exploring_btn: "Erkundung starten",
    no_saved_projects: "Keine gespeicherten Projekte",
    no_saved_projects_desc: "Durchsuchen Sie unsere offenen Projektbeschreibungen und klicken Sie auf das Herz-Symbol, um sie hier zu speichern.",
    no_saved_freelancers: "Keine gespeicherten Freelancer",
    no_saved_freelancers_desc: "Finden Sie Elite-Entwickler oder -Designer und klicken Sie auf das Herz-Symbol, um sie hier zu speichern.",
    vetted_badge: "Geprüft",
    find_projects_header: "Projekte & Angebote finden",
    find_projects_desc: "Durchsuchen Sie aktive Projekte von Kunden und senden Sie Ihre Angebote.",
    search_jobs_placeholder: "Jobs, Kategorien suchen...",
    show_all_btn: "Alle anzeigen",
    ai_matches_btn: "KI-Treffer",
    proposal_submitted_badge: "Vorschlag eingereicht",
    subcategory_label: "Unterkategorie:",
    experience_required_label: "Erforderliche Erfahrung:",
    duration_label: "Dauer:",
    freelancers_label: "Freelancer:",
    submit_proposal_btn: "Vorschlag einreichen",
    hours_limit_label: "Stundenlimit:",
    payout_label: "Auszahlung:",
    checking_btn: "Überprüfung...",
    my_submitted_proposals_header: "Meine eingereichten Vorschläge",
    my_submitted_proposals_desc: "Verfolgen und verwalten Sie den Status Ihrer Gebote für aktive Kundenprojekte.",
    find_projects_btn_label: "Projekte finden",
    total_submitted_metric: "Insgesamt eingereicht",
    accepted_offers_metric: "Angenommene Angebote",
    pending_review_metric: "Unter Überprüfung",
    declined_metric: "Abgelehnt",
    all_proposals_filter: "Alle Vorschläge",
    pending_review_filter: "Unter Überprüfung",
    accepted_hired_filter: "Akzeptiert & Eingestellt",
    declined_cancelled_filter: "Abgelehnt & Storniert",
    search_proposals_placeholder: "Vorschläge suchen...",
    direct_hire_offer: "Direktes Einstellungsangebot",
    offer_invitation_msg: "Angebots-Einladungsnachricht",
    cover_letter_label: "Anschreiben",
    offer_budget_label: "Angebotsbudget:",
    delivery_time_label: "Lieferzeit:",
    accept_offer_btn: "Angebot annehmen",
    decline_btn: "Ablehnen",
    view_details_btn: "Details anzeigen",
    proposals_label_pagination: "Vorschläge",
    "awaiting payment": "Warten auf Zahlung",
    client_prefix: "Kunde:",
    offer_date_prefix: "Angebotsdatum:",
    my_projects_contracts_header: "Meine Projekte & Verträge",
    my_projects_contracts_desc: "Verwalten Sie Ihre aktiven Freelancer-Aufträge, verfolgen Sie Fertigstellungsmeilensteine und zeigen Sie den Kundenverlauf an.",
    ongoing_projects_filter: "Laufende Projekte",
    completed_projects_filter: "Abgeschlossene Projekte",
    cancelled_projects_filter: "Stornierte Projekte",
    all_projects_filter: "Alle Projekte",
    awaiting_approval_status: "Warten auf Genehmigung",
    milestone_progress_label: "Meilensteinfortschritt",
    start_work_btn: "Arbeit starten",
    submit_completed_work_btn: "Abgeschlossene Arbeit einreichen",
    work_submitted_awaiting_approval_status: "Arbeit eingereicht / Wartet auf Genehmigung",
    hired_date_prefix: "Eingestellt:",
    my_clients_tab: "Meine Kunden",
    recommended_clients_tab: "Empfohlene Kunden",
    no_client_history_yet: "Noch kein Kundenverlauf",
    no_client_history_desc: "Schließen Sie Ihre aktiven Verträge ab, um eine Kundenliste aufzubauen.",
    message_client_btn: "Kunden anschreiben",
    no_client_recommendations: "Keine Kundenempfehlungen",
    no_client_recommendations_desc: "Derzeit wurden keine aktiven einstellenden Kunden gefunden, die zu den Empfehlungen passen.",
    direct_hiring_client_label: "Direkt einstellender Kunde",
    view_client_profile_btn: "Kundenprofil anzeigen",
    back_to_projects_btn: "Zurück zu den Projekten",
    open_chat_btn: "Chat öffnen",
    hourly_rate_label: "Stundensatz",
    escrow_remaining_label: "Verbleibendes Treuhandguthaben:",
    progress_label: "Fortschritt",
    client_partner_label: "Kundenpartner",
    contract_scope_desc_label: "Vertragsumfang & Beschreibung",
    service_orders_header: "Service-Bestellungen",
    service_orders_desc: "Überprüfen Sie benutzerdefinierte Projektanforderungen und akzeptieren oder lehnen Sie von Kunden gesendete Bestellungen ab.",
    all_orders_tab: "Alle Bestellungen",
    pending_filter_label: "Ausstehend",
    active_filter_label: "Aktiv",
    completed_filter_label: "Abgeschlossen",
    no_all_orders_found: "Keine Bestellungen gefunden",
    no_pending_orders_found: "Keine ausstehenden Bestellungen gefunden",
    no_active_orders_found: "Keine aktiven Bestellungen gefunden",
    no_completed_orders_found: "Keine abgeschlossenen Bestellungen gefunden",
    no_orders_matching_category_desc: "Sie haben derzeit keine Bestellungen, die dieser Kategorie entsprechen.",
    conversations_sidebar_header: "Unterhaltungen",
    syncing_chats_label: "Chats werden synchronisiert...",
    no_active_chats_title: "Keine aktiven Chats",
    no_active_chats_desc: "Ihre Unterhaltungen beginnen automatisch, wenn ein Vorschlag angenommen wird!",
    select_chat_room_title: "Wählen Sie einen Chatroom",
    select_chat_room_desc: "Wählen Sie eine Kandidatenkonversation aus der Liste aus, um Ergebnisse anzuzeigen und Projektdetails zu besprechen.",
    dispute_system_update_msg: "⚠️ Streitbeilegungssystem-Update",
    custom_payment_offer_received_msg: "📩 Benutzerdefiniertes Zahlungsangebot erhalten",
    no_messages_yet_msg: "Noch keine Nachrichten. Sagen Sie Hallo!",
    custom_payment_offer_label: "Benutzerdefiniertes Zahlungsangebot",
    accept_offer_fund_escrow_btn: "Angebot annehmen & Treuhandkonto finanzieren",
    sent_waiting_client_approval_label: "Gesendet und warten auf Kundengenehmigung",
    offer_accepted_order_active_label: "Angebot angenommen & Bestellung aktiv!",
    platform_notification_header: "Plattform-Benachrichtigung",
    system_notification_header: "System-Benachrichtigung",
    you_label: "Sie",
    user_role_label: "Benutzer",
    proposal_submitted_btn: "Vorschlag eingereicht",
    share_earn_btn: "Teilen & Verdienen",
    best_match_label: "Beste Übereinstimmung",
    match_score_label: "Übereinstimmung",
    view_project_btn: "Projekt anzeigen →",
    analysing_profile_status: "Profil wird analysiert...",
    ai_matching_skills_status: "KI gleicht Ihre Fähigkeiten mit den besten offenen Projekten ab",
    no_strong_matches_found: "Keine starken Übereinstimmungen gefunden",
    no_strong_matches_desc: "Versuchen Sie, Ihr Freelancer-Profil weiter auszufüllen, damit die KI Ihre Expertise besser verstehen kann.",
    saves: "Speicherungen",
    featured_label: "Spitzentalente",
    request_quote: "Angebot anfordern",
    global_trust_eyebrow: "Wir wachsen von Tag zu Tag",
    global_trust_title: "Globales Vertrauen von 1 Million Unternehmen und es werden mehr",
    global_trust_desc: "Verbinden Sie sich mit qualifizierten Fachkräften, optimieren Sie die Zusammenarbeit und schalten Sie den Erfolg frei. Melden Sie sich jetzt an und definieren Sie Ihre Arbeitserfahrung neu!",
    global_trust_check_1: "Verbinden Sie sich mit Profis, arbeiten Sie besser zusammen, haben Sie schneller Erfolg",
    global_trust_check_2: "Definieren Sie Arbeit neu, melden Sie sich jetzt an für eine bessere Erfahrung",
    global_trust_check_3: "Optimieren Sie die Zusammenarbeit, schalten Sie den Erfolg frei",
    global_trust_check_4: "Machen Sie mit, definieren Sie Ihre Arbeitserfahrung neu"
  }
};

  const t = (key: string, defaultVal?: string) => {
    if (!key) return defaultVal || "";
    const trimmed = key.trim();
    const cleanKey = trimmed.toLowerCase();

    // 1. Check API loaded translations map
    if (translations[cleanKey]) return translations[cleanKey];
    if (translations[trimmed]) return translations[trimmed];

    // 2. Check Static Fallback Dictionary for active lang
    const langDict = STATIC_FALLBACK_DICTIONARY[lang.toUpperCase()];
    if (langDict) {
      if (langDict[cleanKey]) return langDict[cleanKey];
      if (langDict[trimmed]) return langDict[trimmed];
    }

    return defaultVal || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        lang,
        direction,
        currency,
        currencySymbol,
        currencyRate,
        translations,
        activeLanguages,
        currencies,
        t,
        changeLanguage,
        changeCurrency,
        convertPrice,
        formatPrice,
        loading
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextProps {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    return {
      lang: "EN",
      direction: "LTR",
      currency: "USD",
      currencySymbol: "$",
      currencyRate: 1.0,
      translations: {},
      activeLanguages: [{ code: "EN", name: "English", direction: "LTR" }],
      currencies: [{ code: "USD", name: "US Dollar", symbol: "$", rate: 1 }],
      t: (key: string, fallback?: string) => fallback || key,
      changeLanguage: () => {},
      changeCurrency: () => {},
      convertPrice: (price: number) => price,
      formatPrice: (price: number) => `$${price.toFixed(2)}`,
      loading: false
    };
  }
  return context;
}
