"use client";

import React from "react";
import ProposalsTab from "@/components/dashboard/ProposalsTab";
import { useDashboard } from "../DashboardContext";

export default function ProposalsPage() {
  const {
    userRole,
    isCreatingJob,
    setIsCreatingJob,
    postJobTitle,
    setPostJobTitle,
    postJobBudget,
    setPostJobBudget,
    postJobCategoryId,
    setPostJobCategoryId,
    handlePostJobCategoryChange,
    postJobSubCategoryId,
    setPostJobSubCategoryId,
    handlePostJobSubCategoryChange,
    postJobSubCategories,
    postJobDescription,
    setPostJobDescription,
    postJobExpLevel,
    setPostJobExpLevel,
    postJobStep,
    setPostJobStep,
    postJobType,
    setPostJobType,
    postJobMilestoneType,
    setPostJobMilestoneType,
    postJobMinBudget,
    setPostJobMinBudget,
    postJobMaxBudget,
    setPostJobMaxBudget,
    postJobDuration,
    setPostJobDuration,
    postJobLocation,
    setPostJobLocation,
    postJobNumFreelancers,
    setPostJobNumFreelancers,
    postJobAvailableSkills,
    postJobSelectedSkills,
    setPostJobSelectedSkills,
    handlePostJobToggleSkill,
    postJobAvailableLanguages,
    postJobSelectedLanguages,
    setPostJobSelectedLanguages,
    handlePostJobToggleLanguage,
    postJobMaxHours,
    setPostJobMaxHours,
    postJobPaymentMode,
    setPostJobPaymentMode,
    clientJobs,
    loadingClientJobs,
    fetchClientJobs,
    selectedProjectDetails,
    setSelectedProjectDetails,
    projectProposals,
    loadingProjectProposals,
    handleUpdateProposalStatus,
    setSelectedFreelancerProfile,
    freelancerProposals,
    loadingFreelancerProposals,
    fetchFreelancerProposals,
    gigCategories,
    triggerToast,
    setActiveTab,
    editingDraftJobId,
    setEditingDraftJobId
  } = useDashboard();

  return (
    <ProposalsTab
      userRole={userRole}
      isCreatingJob={isCreatingJob}
      setIsCreatingJob={setIsCreatingJob}
      postJobTitle={postJobTitle}
      setPostJobTitle={setPostJobTitle}
      postJobBudget={postJobBudget}
      setPostJobBudget={setPostJobBudget}
      postJobCategoryId={postJobCategoryId}
      setPostJobCategoryId={setPostJobCategoryId}
      handlePostJobCategoryChange={handlePostJobCategoryChange}
      postJobSubCategoryId={postJobSubCategoryId}
      setPostJobSubCategoryId={setPostJobSubCategoryId}
      handlePostJobSubCategoryChange={handlePostJobSubCategoryChange}
      postJobSubCategories={postJobSubCategories}
      postJobDescription={postJobDescription}
      setPostJobDescription={setPostJobDescription}
      postJobExpLevel={postJobExpLevel}
      setPostJobExpLevel={setPostJobExpLevel}
      postJobStep={postJobStep}
      setPostJobStep={setPostJobStep}
      postJobType={postJobType}
      setPostJobType={setPostJobType}
      postJobMilestoneType={postJobMilestoneType}
      setPostJobMilestoneType={setPostJobMilestoneType}
      postJobMinBudget={postJobMinBudget}
      setPostJobMinBudget={setPostJobMinBudget}
      postJobMaxBudget={postJobMaxBudget}
      setPostJobMaxBudget={setPostJobMaxBudget}
      postJobDuration={postJobDuration}
      setPostJobDuration={setPostJobDuration}
      postJobLocation={postJobLocation}
      setPostJobLocation={setPostJobLocation}
      postJobNumFreelancers={postJobNumFreelancers}
      setPostJobNumFreelancers={setPostJobNumFreelancers}
      postJobAvailableSkills={postJobAvailableSkills}
      postJobSelectedSkills={postJobSelectedSkills}
      setPostJobSelectedSkills={setPostJobSelectedSkills}
      handlePostJobToggleSkill={handlePostJobToggleSkill}
      postJobAvailableLanguages={postJobAvailableLanguages}
      postJobSelectedLanguages={postJobSelectedLanguages}
      setPostJobSelectedLanguages={setPostJobSelectedLanguages}
      handlePostJobToggleLanguage={handlePostJobToggleLanguage}
      postJobMaxHours={postJobMaxHours}
      setPostJobMaxHours={setPostJobMaxHours}
      postJobPaymentMode={postJobPaymentMode}
      setPostJobPaymentMode={setPostJobPaymentMode}
      clientJobs={clientJobs}
      loadingClientJobs={loadingClientJobs}
      fetchClientJobs={fetchClientJobs}
      selectedProjectDetails={selectedProjectDetails}
      setSelectedProjectDetails={setSelectedProjectDetails}
      projectProposals={projectProposals}
      loadingProjectProposals={loadingProjectProposals}
      handleUpdateProposalStatus={handleUpdateProposalStatus}
      setSelectedFreelancerProfile={setSelectedFreelancerProfile}
      freelancerProposals={freelancerProposals}
      loadingFreelancerProposals={loadingFreelancerProposals}
      fetchFreelancerProposals={fetchFreelancerProposals}
      gigCategories={gigCategories}
      triggerToast={triggerToast}
      setActiveTab={setActiveTab}
      editingDraftJobId={editingDraftJobId}
      setEditingDraftJobId={setEditingDraftJobId}
    />
  );
}
